spring:
  application:
    name: urlshortener
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://dpg-cqblkfeehbks73dqdtf0-a:5432/urlshortener_1iiq
      username: urlshortener_1iiq_user
      password: ttYxcPk7xcicGqsLOvOalVgk20n7JeIx
      maximum-pool-size: 30
      minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  data:
    redis:
      host: red-cqblm3qju9rs73938fsg
      port: 6379
    jdbc:
      dialect: postgresql
server:
  servlet:
    context-path: /api/v1

